### ISSUE TITLE
Dragon/rider care

### ISSUE THREAD

**Issue by HeartQEssence** [DestinyWeaves/Guidebook#14]
In the original dragon notes :https://docs.google.com/document/d/1mkTcFCOcpJ31jwmUhjG2eUZaMIpbrGSQ6pe4e-YGdiQ/edit?usp=drivesdk

We have intersting information about dragons (illnesses care act) these..

**Comment by AJMansfield** [comment]
I don't seem to have access to that document. LMK once you've granted me access and I'll port it over.
